[package]
name = "bandit"
version = "0.1.0"
authors = ["Ryuta-Yamamoto <43087138+Ryuta-Yamamoto@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statrs = "0.13.0"
rand = "0.7.3"
